import React from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

export interface AboutProps {}

export default function About(props: AboutProps) {
	return (
		<div className={styles.container}>
			<Head>
				<title>About</title>
				<meta name="description" content="Generated by About" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>About Page</h1>
			</main>
		</div>
	);
}
